import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {createServer} from 'node:http';import {resolve,extname} from 'node:path';import {chromium,expect} from '@playwright/test';import {keccak256} from 'viem';
const cfg=JSON.parse(await fs.readFile('initial-stake/config.json'));const codes=JSON.parse(await fs.readFile('test/initial-stake-code.json'));const tokenCode=codes.find(x=>x.id===1).result,vaultCode=codes.find(x=>x.id===2).result;assert.equal(keccak256(tokenCode),cfg.tokenCodeHash);assert.equal(keccak256(vaultCode),cfg.vaultCodeHash);
const account='0x1111111111111111111111111111111111111111',amount=100000n*10n**18n,w=n=>'0x'+BigInt(n).toString(16).padStart(64,'0');let server,browser,origin;
before(async()=>{const root=resolve('.');server=createServer(async(req,res)=>{try{let p=resolve(root,'.'+new URL(req.url,'http://localhost').pathname);assert(p.startsWith(root+'/'));if((await fs.stat(p)).isDirectory())p+='/index.html';res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'})[extname(p)]??'application/json');res.end(await fs.readFile(p));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({executablePath:process.env.STAKED_TEST_CHROME,args:['--no-sandbox']});});after(async()=>{await browser?.close();server?.close();});
async function fixture(options={}){const s={allowance:0n,stake:0n,balance:amount+1n,nonce:0,sent:[],txs:{},...options};const context=await browser.newContext(),page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.exposeFunction('fakeRpc',async({method,params=[]})=>{if(method==='eth_chainId')return s.chain??'0x2105';if(['eth_accounts','eth_requestAccounts'].includes(method))return [account];if(method==='eth_getCode')return params[0].toLowerCase()===cfg.token.toLowerCase()?tokenCode:vaultCode;if(method==='eth_getTransactionCount')return '0x'+s.nonce.toString(16);if(method==='eth_blockNumber')return '0x102';if(method==='eth_estimateGas')return '0x30000';if(method==='eth_getTransactionByHash')return s.txs[params[0]];if(method==='eth_getTransactionReceipt')return {status:'0x1',transactionHash:params[0],blockNumber:'0x100'};
if(method==='eth_call'){const t=params[0],sel=t.data.slice(0,10);if(sel==='0x8da5cb5b')return '0x'+cfg.safe.slice(2).toLowerCase().padStart(64,'0');if(sel==='0x313ce567')return w(18);if(sel==='0x70a08231')return w(t.to.toLowerCase()===cfg.token.toLowerCase()?s.balance:s.stake);if(sel==='0xdd62ed3e')return w(s.allowance);if(sel==='0x095ea7b3')return w(1);if(sel==='0xa694fc3a'){assert.equal(s.allowance,amount);return '0x';}}
if(method==='eth_sendTransaction'){const t=params[0];s.sent.push(t);if(s.uncertain)throw Error('uncertain RPC');if(t.to.toLowerCase()===cfg.token.toLowerCase()){assert.equal(t.data,'0x095ea7b3'+cfg.vault.slice(2).toLowerCase().padStart(64,'0')+w(amount).slice(2));s.allowance=amount;}else{assert.equal(t.data,'0xa694fc3a'+w(amount).slice(2));s.stake=amount;s.allowance=0n;s.balance-=amount;}const hash='0x'+String(++s.nonce).padStart(64,'0');s.txs[hash]={...t,input:t.data};return hash;}throw Error('Unhandled '+method);});await page.addInitScript(()=>{window.ethereum={isRabby:true,request:r=>window.fakeRpc(r),on:()=>{}};});await page.goto(origin+'/initial-stake/');await page.locator('#connect').click();return {page,context,s,errors};}
test('exact approval and stake require separate clicks; no duplicate or lock reset',async()=>{const f=await fixture();await expect(f.page.locator('#approve')).toBeEnabled();assert.equal(f.s.sent.length,0);await f.page.locator('#approve').click();await expect(f.page.locator('#status')).toContainText('submitted');await f.page.locator('#check').click();await expect(f.page.locator('#stake')).toBeEnabled();await f.page.locator('#stake').click();await expect(f.page.locator('#status')).toContainText('submitted');await f.page.locator('#check').click();await expect(f.page.locator('#status')).toContainText('staked successfully');assert.equal(f.s.sent.length,2);assert.equal(f.s.allowance,0n);await f.page.locator('#check').click();await expect(f.page.locator('#stake')).toBeDisabled();assert.deepEqual(f.errors,[]);await f.context.close();});
test('wrong network and existing stake block sends',async()=>{for(const options of [{chain:'0x1'},{stake:1n}]){const f=await fixture(options);await expect(f.page.locator('#approve')).toBeDisabled();await expect(f.page.locator('#stake')).toBeDisabled();assert.equal(f.s.sent.length,0);await f.context.close();}});
test('ambiguous send survives reload and prevents retry',async()=>{const f=await fixture({uncertain:true});await expect(f.page.locator('#approve')).toBeEnabled();await f.page.locator('#approve').click();await expect(f.page.locator('#status')).toContainText('failed');await f.page.reload();await f.page.locator('#connect').click();await expect(f.page.locator('#status')).toContainText('may have been submitted');await expect(f.page.locator('#approve')).toBeDisabled();assert.equal(f.s.sent.length,1);await f.context.close();});
