import {keccak256} from 'viem';
import config from './config.json';
const {token,vault,safe,tokenCodeHash,vaultCodeHash}=config;
const amount=100000n*10n**18n,word=n=>BigInt(n).toString(16).padStart(64,'0'),addr=a=>a.slice(2).toLowerCase().padStart(64,'0');
const approveData='0x095ea7b3'+addr(vault)+word(amount),stakeData='0xa694fc3a'+word(amount);
const $=id=>document.getElementById(id),say=t=>{$('status').textContent=t;};
let provider,account,busy=false,ready=false,version=0,stage,storeKey;
const providers=[];window.addEventListener('eip6963:announceProvider',e=>{if(e.detail?.info?.rdns==='io.rabby')providers.push(e.detail.provider);});window.dispatchEvent(new Event('eip6963:requestProvider'));
class CheckError extends Error{}const check=(ok,msg)=>{if(!ok)throw new CheckError(msg);};
const eq=(a,b)=>a?.toLowerCase()===b?.toLowerCase();const saved=()=>{const s=localStorage.getItem(storeKey);return s?JSON.parse(s):null;};
function buttons(){$('connect').disabled=busy||!!account;$('check').disabled=busy||!account;$('approve').disabled=busy||!ready||stage!=='approve';$('stake').disabled=busy||!ready||stage!=='stake';$('recover').disabled=busy||!account;}
async function action(fn){if(busy)return;busy=true;ready=false;buttons();try{await fn();}catch(e){say(e instanceof CheckError?e.message:e?.code===4001?'Request declined. Check progress before trying again.':'Wallet or network check failed. Check progress; if a request may have been sent, recover its hash before retrying.');}finally{busy=false;buttons();}}
const rpc=(method,params=[])=>provider.request({method,params});
async function identity(){check(await rpc('eth_chainId')==='0x2105','Switch Rabby to Base, then Check progress.');const accounts=await rpc('eth_accounts');check(eq(accounts[0],account),'Rabby account changed. Return to the connected account or reload.');}
async function call(to,data){return rpc('eth_call',[{to,data},'latest']);}
async function state(){await identity();check(eq(keccak256(await rpc('eth_getCode',[token,'latest'])),tokenCodeHash),'Token code differs from the verified deployment. Stop.');check(eq(keccak256(await rpc('eth_getCode',[vault,'latest'])),vaultCodeHash),'Vault code differs from the verified deployment. Stop.');check(eq('0x'+(await call(vault,'0x8da5cb5b')).slice(-40),safe),'Vault owner differs from the expected Safe. Stop.');check(BigInt(await call(token,'0x313ce567'))===18n,'Unexpected token decimals. Stop.');
return {balance:BigInt(await call(token,'0x70a08231'+addr(account))),allowance:BigInt(await call(token,'0xdd62ed3e'+addr(account)+addr(vault))),stake:BigInt(await call(vault,'0x70a08231'+addr(account)))};}
function link(hash){const a=document.createElement('a');a.href='https://basescan.org/tx/'+hash;a.target='_blank';a.rel='noopener noreferrer';a.textContent='View transaction on BaseScan';$('receipt').replaceChildren(a);}
async function progress(){const s=await state(),p=saved();if(p){if(p.hash){await verify(p.hash);return;}say('A wallet request may have been submitted. Paste its transaction hash to recover; do not send a duplicate.');return;}
if(s.stake>0n){say('This wallet already has a V3 stake. No additional stake is enabled here, so its lock will not be reset.');return;}
check(s.balance>=amount,'Wallet balance is below 100,000 STAKED.');stage=s.allowance===amount?'stake':'approve';ready=true;say(stage==='approve'?'Ready: approve exactly 100,000 STAKED to the verified V3 vault.':'Approval is exactly 100,000 STAKED. Ready to stake it with a new seven-day lock.');}
async function verify(hash){check(/^0x[0-9a-fA-F]{64}$/.test(hash),'Enter a valid transaction hash.');await identity();const p=saved();check(p,'No pending transaction is recorded in this browser.');const tx=await rpc('eth_getTransactionByHash',[hash]);check(tx&&eq(tx.from,account)&&eq(tx.to,p.to)&&eq(tx.input,p.data)&&BigInt(tx.value)===0n&&BigInt(tx.nonce)===BigInt(p.nonce),'Transaction does not match the recorded request. Stop.');p.hash=hash;localStorage.setItem(storeKey,JSON.stringify(p));link(hash);
const r=await rpc('eth_getTransactionReceipt',[hash]);if(!r){say('Transaction is pending. Wait, then Check progress.');return;}
if(r.status!=='0x1'){localStorage.removeItem(storeKey);throw new CheckError('Transaction reverted. Check progress before trying again.');}
check(eq(r.transactionHash,hash),'Receipt hash mismatch.');if(BigInt(await rpc('eth_blockNumber'))<=BigInt(r.blockNumber)){say('Transaction mined. Wait for another Base block, then Check progress.');return;}
const s=await state();if(p.kind==='approve')check(s.allowance===amount,'Approval receipt succeeded but allowance differs. Stop.');else{check(s.stake===amount,'Stake receipt succeeded but staked amount differs. Stop.');check(s.allowance===0n,'Stake completed but remaining allowance is not zero. Stop.');}
localStorage.removeItem(storeKey);
if(p.kind==='stake'){say('100,000 STAKED staked successfully. Save the BaseScan receipt.');return;}
await progress();}
async function send(kind){const epoch=version,s=await state();check(s.stake===0n,'An existing stake was found. Stop to avoid resetting its lock.');check(s.balance>=amount,'Insufficient STAKED.');check(!saved(),'Recover the previous request before sending another.');if(kind==='stake')check(s.allowance===amount,'Approve exactly 100,000 STAKED first.');
const to=kind==='approve'?token:vault,data=kind==='approve'?approveData:stakeData;
const nonce=await rpc('eth_getTransactionCount',[account,'pending']);check(nonce===await rpc('eth_getTransactionCount',[account,'latest']),'Wait for pending wallet transactions to finish.');const tx={from:account,to,data,value:'0x0',chainId:'0x2105',nonce};await rpc('eth_call',[tx,'latest']);const estimate=BigInt(await rpc('eth_estimateGas',[tx]));tx.gas='0x'+((estimate*120n+99n)/100n).toString(16);await identity();check(epoch===version,'Wallet account or network changed during checks. Check progress again.');
const p={kind,to,data,nonce};localStorage.setItem(storeKey,JSON.stringify(p));let hash;try{hash=await rpc('eth_sendTransaction',[tx]);}catch(e){if(e?.code===4001)localStorage.removeItem(storeKey);throw e;}check(/^0x[0-9a-fA-F]{64}$/.test(hash),'Wallet returned no valid hash. Recover the request before retrying.');p.hash=hash;localStorage.setItem(storeKey,JSON.stringify(p));link(hash);say('Transaction submitted. Wait for confirmation, then Check progress.');}
$('connect').onclick=()=>action(async()=>{provider=providers[0]??(window.ethereum?.isRabby?window.ethereum:undefined);check(provider,'Open this page in desktop Chrome with Rabby installed.');const accounts=await rpc('eth_requestAccounts');check(accounts?.[0],'No Rabby account selected.');account=accounts[0];storeKey='staked-initial-v3:'+account.toLowerCase()+':'+vault.toLowerCase();$('wallet').textContent=account;provider.on?.('accountsChanged',()=>{version++;ready=false;buttons();});provider.on?.('chainChanged',()=>{version++;ready=false;buttons();});await progress();});
$('check').onclick=()=>action(progress);const lockedSend=kind=>{check(navigator.locks,'Browser locking is unavailable. Use desktop Chrome.');return navigator.locks.request(storeKey,{ifAvailable:true},lock=>{check(lock,'Another tab has a signing request open.');return send(kind);});};$('approve').onclick=()=>action(()=>lockedSend('approve'));$('stake').onclick=()=>action(()=>lockedSend('stake'));$('recover').onclick=()=>action(()=>verify($('hash').value.trim()));
$('token').textContent=token;$('vault').textContent=vault;buttons();
